server:
  port: 8080
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/blogdb
    password: root
  jpa:
    generate-ddl : on
    hibernate:
      ddl-auto: update
    show-sql : true
    properties:
      hibernate:
        format-sql : true
logging:
  level:
    org:
      hibernate:
        SQL : DEBUG