server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url : jdbc:h2:file:./blob.db
  jpa:
    generate-ddl : on
    hibernate:
      ddl-auto: update
    show-sql : true
    properties:
      hibernate:
        format-sql : true
logging:
  level:
    org:
      hibernate:
        SQL : DEBUG